ClothingBrandApp/Controllers/FavoriteController.cs
using ClothingBrand.Services.Core.Interfaces;
using ClothingBrandApp.Web.ViewModels.Product;
using Microsoft.AspNetCore.Mvc;

namespace ClothingBrandApp.Web.Controllers
{
    public class FavoriteController : BaseController
    {
        private readonly IFavoriteService favoriteService;
        private readonly IShoppingCartService shoppingCartService;
        public FavoriteController(IFavoriteService favoriteService, IShoppingCartService shoppingCartService) 
        {
            this.favoriteService = favoriteService;
            this.shoppingCartService = shoppingCartService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                string? userId = this.GetUserId();
                if (userId == null)
                {
                    return this.Forbid();
                }

                IEnumerable<ProductIndexViewModel>? userFavProducts = await this.favoriteService
                    .GetUserFavoriteProductsAsync(userId);
                if (this.IsUserAuthenticated() && userFavProducts != null)
                {
                    foreach (ProductIndexViewModel productIndexVM in userFavProducts)
                    {
                        productIndexVM.IsFavorite = await this.favoriteService
                            .IsProductAddedToFavorites(productIndexVM.Id, this.GetUserId()!);
                        productIndexVM.IsInShoppingCart = await this.shoppingCartService
                            .IsProductAddedToShoppingCart(productIndexVM.Id, this.GetUserId()!);
                    }
                }
                return this.View(userFavProducts);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index), "Home");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Add(Guid? productId)
        {
            try
            {
                string? userId = this.GetUserId();
                if (userId == null)
                {
                    // Not a valid case, added as defensive mechanism
                    return this.Forbid();
                }

                bool result = await this.favoriteService
                    .AddProductToUserFavoritesAsync(productId, userId);
                if (result == false)
                {
                    // TODO: Add JS notifications
                    return this.RedirectToAction(nameof(Index), "Shop");
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.RedirectToAction(nameof(Index), "Shop");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid? productId)
        {
            try
            {
                string? userId = this.GetUserId();
                if (userId == null)
                {
                    // Not a valid case, added as defensive mechanism
                    return this.Forbid();
                }

                bool result = await this.favoriteService
                    .DeleteProductFromUserFavoritesAsync(productId, userId);
                if (result == false)
                {
                    // TODO: Add JS notifications
                    return this.RedirectToAction(nameof(Index), "Shop");
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);

                return this.RedirectToAction(nameof(Index));
            }
        }
    }
}

ClothingBrandApp/Controllers/ShopController.cs
using ClothingBrand.Services.Core.Interfaces;
using ClothingBrandApp.Web.Controllers;
using ClothingBrandApp.Web.ViewModels.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static ClothingBrandApp.GCommon.ApplicationConstants;

namespace ClothingBrand.Web.Controllers
{
    public class ShopController : BaseController
    {
        private readonly IShopService shopService;
        private readonly ICategoryService categoryService;
        private readonly IFavoriteService favoriteService;
        private readonly IShoppingCartService shoppingCartService;

        public ShopController(IShopService shopService,
            ICategoryService categoryService, IFavoriteService favoriteService, IShoppingCartService shoppingCartService)
        {
            this.shopService = shopService;
            this.categoryService = categoryService;
            this.favoriteService = favoriteService;
            this.shoppingCartService = shoppingCartService;        
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            IEnumerable<ProductIndexViewModel> allProducts = await shopService
                .GetAllProductsAsync();
            if (this.IsUserAuthenticated())
            {
                foreach (ProductIndexViewModel productIndexVM in allProducts)
                {
                    productIndexVM.IsFavorite = await this.favoriteService
                        .IsProductAddedToFavorites(productIndexVM.Id, this.GetUserId()!);
                    productIndexVM.IsInShoppingCart = await this.shoppingCartService
                        .IsProductAddedToShoppingCart(productIndexVM.Id, this.GetUserId()!);
                }
            }
            return View(allProducts);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid? id)
        {
            try
            {
                ProductDetailsViewModel? productDetails = await this.shopService
                    .GetProductDetailsByIdAsync(id);
                if (this.IsUserAuthenticated() && productDetails != null)
                {
                    productDetails.IsFavorite = await this.favoriteService
                            .IsProductAddedToFavorites(productDetails.Id, this.GetUserId()!);
                    productDetails.IsInShoppingCart = await this.shoppingCartService
                        .IsProductAddedToShoppingCart(productDetails.Id, this.GetUserId()!);

                }
                if (productDetails == null)
                {
                    return this.RedirectToAction(nameof(Index));
                }

                return this.View(productDetails);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "An error occurred while trying to load the product details.";

                return this.RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> MenCollection()
        {
            const string  genderName = "Men";
            IEnumerable<ProductIndexViewModel> allProducts = await shopService
                .GetProductsByGenderAsync(genderName);
            if (this.IsUserAuthenticated())
            {
                foreach (ProductIndexViewModel productIndexVM in allProducts)
                {
                    productIndexVM.IsFavorite = await this.favoriteService
                        .IsProductAddedToFavorites(productIndexVM.Id, this.GetUserId()!);
                    productIndexVM.IsInShoppingCart = await this.shoppingCartService
                        .IsProductAddedToShoppingCart(productIndexVM.Id, this.GetUserId()!);
                }
            }
            return View(allProducts);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> WomenCollection()
        {
            const string genderName = "Women";
            IEnumerable<ProductIndexViewModel> allProducts = await shopService
                .GetProductsByGenderAsync(genderName);
            if (this.IsUserAuthenticated())
            {
                foreach (ProductIndexViewModel productIndexVM in allProducts)
                {
                    productIndexVM.IsFavorite = await this.favoriteService
                        .IsProductAddedToFavorites(productIndexVM.Id, this.GetUserId()!);
                    productIndexVM.IsInShoppingCart = await this.shoppingCartService
                        .IsProductAddedToShoppingCart(productIndexVM.Id, this.GetUserId()!);
                }
            }
            return View(allProducts);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> KidsCollection()
        {
            const string genderName = "Kids";
            IEnumerable<ProductIndexViewModel> allProducts = await shopService
                .GetProductsByGenderAsync(genderName);
            if (this.IsUserAuthenticated())
            {
                foreach (ProductIndexViewModel productIndexVM in allProducts)
                {
                    productIndexVM.IsFavorite = await this.favoriteService
                        .IsProductAddedToFavorites(productIndexVM.Id, this.GetUserId()!);
                    productIndexVM.IsInShoppingCart = await this.shoppingCartService
                        .IsProductAddedToShoppingCart(productIndexVM.Id, this.GetUserId()!);
                }
            }
            return View(allProducts);
        }
    }
}

ClothingBrandApp/Controllers/ShoppingCartController.cs
using ClothingBrand.Services.Core.Interfaces;
using ClothingBrandApp.Web.Controllers;
using Microsoft.AspNetCore.Mvc;

public class ShoppingCartController : BaseController
{
    private readonly IShoppingCartService shoppingCartService;

    public ShoppingCartController(IShoppingCartService shoppingCartService)
    {
        this.shoppingCartService = shoppingCartService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        try
        {
            string? userId = this.GetUserId();
            if (userId == null)
            {
                return this.Forbid();
            }
            var userShoppingCartProducts = await this.shoppingCartService
                .GetAllProductsInShoppingCartAsync(userId);
            return View(userShoppingCartProducts);
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
            return RedirectToAction(nameof(Index), "Home");
        }
    }

    [HttpPost]
    public async Task<IActionResult> Add(Guid? productId)
    {
        try
        {
            string? userId = this.GetUserId();
            if (userId == null)
            {
                // Not a valid case, added as defensive mechanism
                return this.Forbid();
            }

            bool result = await this.shoppingCartService
                    .AddProductToShoppingCartAsync(productId, userId);
            if (result == false)
            {
                TempData["ErrorMessage"] = "An error occurred while trying to add the product.";
                return this.RedirectToAction(nameof(Index), "Shop");
            }

            return this.RedirectToAction(nameof(Index));
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);

            return this.RedirectToAction(nameof(Index), "Home");
        }
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid? productId)
    {
        try
        {
            string? userId = this.GetUserId();
            if (userId == null)
            {
                // Not a valid case, added as defensive mechanism
                return this.Forbid();
            }

            bool result = await this.shoppingCartService
                .DeleteProductFromShoppingCartAsync(productId, userId);
            if (result == false)
            {
                TempData["ErrorMessage"] = "An error occurred while trying to delete the product.";
                return this.RedirectToAction(nameof(Index), "Home");
            }

            return this.RedirectToAction(nameof(Index));
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);

            return this.RedirectToAction(nameof(Index), "Home");
        }
    }
}

ClothingBrandApp/Controllers/WarehouseController.cs
using ClothingBrand.Services.Core.Interfaces;
using ClothingBrandApp.Web.ViewModels.Warehouse;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using static ClothingBrandApp.GCommon.ApplicationConstants;

namespace ClothingBrandApp.Web.Controllers
{
    [Authorize(Roles = $"{AdminRoleName},{ManagerRoleName}")]
    [AutoValidateAntiforgeryToken]
    public class WarehouseController : Controller
    {
        private readonly IWarehouseService warehouseService;

        public WarehouseController(IWarehouseService warehouseService)
        {
            this.warehouseService = warehouseService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                IEnumerable<WarehouseIndexViewModel> allWarehouses = await this.warehouseService
                .GetAllWarehousesViewAsync();

                return View(allWarehouses);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);

                return this.RedirectToAction(nameof(Index), "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Stock(string? id)
        {
            try
            {
                WarehouseStockViewModel? clothingWarehouses = await this.warehouseService
                    .GetWarehouseProductsAsync(id);
                if (clothingWarehouses == null)
                {
                    return this.RedirectToAction(nameof(Index));
                }

                return this.View(clothingWarehouses);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);

                return this.RedirectToAction(nameof(Index));
            }
        }
    }
}

ClothingBrandApp/Views/Shared/NotFoundError.cshtml
@{
    ViewData["Title"] = "Not Found";
}

@section Styles {
    <link rel="stylesheet" href="~/css/errors.css" />
}

<div class="custom-404-wrapper">
    <div class="error-container">
        <div class="error-code">404</div>
        <div class="error-message">Page Not Found</div>
        <div class="error-description">
            Oops! The page you're looking for doesn't exist or has been moved.<br />
            Please check the URL or go back to the homepage.
        </div>
        <a asp-controller="Home" asp-action="Index" class="btn-home">Return to Homepage</a>
    </div>
</div>

ClothingBrandApp/Views/Shared/UnauthorizedError.cshtml
@{
    ViewData["Title"] = "Access Denied";
}

@section Styles {
    <link rel="stylesheet" href="~/css/errors.css" />
}

<div class="custom-404-wrapper">
    <div class="error-container">
        <div class="error-code">403</div>
        <div class="error-message">Access Denied</div>
        <div class="error-description">
            You do not have permission to view this page.<br />
            If you believe this is a mistake, please contact the administrator.
        </div>
        <a asp-controller="Home" asp-action="Index" class="btn-home">Return to Homepage</a>
    </div>
</div>

ClothingBrandApp/Views/Shared/_Layout.cshtml
@{  
	int currentYear = DateTime.UtcNow.Year;  
	string footerNote = (2025 == currentYear) ? $"{currentYear}" : $"{2025} - {currentYear}";  
}  

<!DOCTYPE html>
<html lang="en">
<head>
		<meta charset="utf-8" />  
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />  
		<title>@ViewData["Title"]</title>  
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />  
		<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />  
		<link rel="stylesheet" href="~/css/user.css" asp-append-version="true" />  
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

	@await RenderSectionAsync("Styles", false)  
	<style>
		html, body {
			height: 100%;
		}
		body {
			display: flex;
			flex-direction: column;
			min-height: 100vh;
		}
		.main-content-container {
			flex: 1 0 auto;
		}
		.site-footer {
			background: #23272b;
			color: #f8f9fa;
			padding: 0.5rem 0 0.5rem 0;
			border-top: 4px solid #ffc107;
			font-size: 1rem;
			letter-spacing: 0.02em;
			box-shadow: 0 -2px 12px rgba(0,0,0,0.08);
			flex-shrink: 0;
		}
		.site-footer .footer-brand {
			font-weight: 600;
			font-size: 1.2rem;
			color: #ffc107;
			letter-spacing: 0.05em;
		}
		.site-footer .footer-note {
			margin-top: 0.5rem;
			font-size: 0.98rem;
			color: #adb5bd;
		}
	</style>
</head>  
<body>  
	<header>  
		<partial name="_NotificationsPartial" />
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-lg">  
			<div class="container-fluid">  
				<a class="navbar-brand fw-bold text-warning" asp-area="" asp-controller="Home" asp-action="Index">  
					<i class="bi bi-bag-fill"></i> TrendWear  
				</a>  
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"  
						aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">  
					<span class="navbar-toggler-icon"></span>  
				</button>  
				<div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">  
					<ul class="navbar-nav flex-grow-1">  
						<li class="nav-item">  
							<a class="nav-link text-light" asp-area="" asp-controller="Shop" asp-action="Index">  
								<i class="bi bi-bag"></i> Shop  
							</a>  
						</li>  
						<li class="nav-item dropdown">  
							<a class="nav-link dropdown-toggle text-light" href="#" id="collectionsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">  
								<i class="bi bi-collection"></i> Collections  
							</a>  
							<ul class="dropdown-menu" aria-labelledby="collectionsDropdown">  
								<li>  
									<a class="dropdown-item" asp-area="" asp-controller="Shop" asp-action="MenCollection">Men</a>
								</li>  
								<li>  
									<a class="dropdown-item" asp-area="" asp-controller="Shop" asp-action="WomenCollection">Women</a>
								</li>  
								<li>  
									<a class="dropdown-item" asp-area="" asp-controller="Shop" asp-action="KidsCollection">Kids</a>
								</li>  
							</ul>  
						</li>  
						@if (User?.Identity?.IsAuthenticated ?? false)
						{
							<li class="nav-item">
								<a class="nav-link text-light" asp-area="" asp-controller="Favorite" asp-action="Index">
									<i class="bi bi-heart"></i> Favorites
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-light" asp-area="" asp-controller="ShoppingCart" asp-action="Index">
									<i class="bi bi-cart"></i> Shopping Cart
								</a>
							</li>
							@if (User.IsInRole("Admin") || User.IsInRole("Manager"))
							{
								<li class="nav-item">
									<a class="nav-link text-light" asp-area="" asp-controller="Warehouse" asp-action="Index">
										<i class="bi bi-box-seam"></i> Warehouses

									</a>
								</li>
							}
							@if (User.IsInRole("Admin"))
							{
								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle text-light fw-bold" href="#" id="manageDropdown"
									   role="button" data-bs-toggle="dropdown" aria-expanded="false">
										<i class="bi bi-gear-fill"></i> Admin
									</a>
									<ul class="dropdown-menu dropdown-menu-dark border-0">
										<li>
											<a class="dropdown-item" asp-area="Admin" asp-controller="UserManagement" asp-action="Index">
												<i class="bi bi-people-fill"></i> Manage Users
											</a>
										</li>
										<li>
											<a class="dropdown-item" asp-area="Admin" asp-controller="WarehouseManagement" asp-action="Manage">
												<i class="bi bi-box-seam"></i> Manage Warehouses
											</a>
										</li>
										<li>
											<a class="dropdown-item" asp-area="Admin" asp-controller="ProductManagement" asp-action="Manage">
												<i class="bi bi-bag-check-fill"></i> Manage Products
											</a>
										</li>
									</ul>
								</li>
							}
						}

					</ul>  
					<partial name="_LoginPartial" />  
				</div>  
			</div>  
		</nav>  
	</header>  
	<div class="container main-content-container">  
		<main role="main" class="pb-3">  
			@RenderBody()  
		</main>  
	</div>  

	<footer class="site-footer mt-5">
		<div class="container text-center">
			<div class="footer-brand mb-2">
				<i class="bi bi-bag-fill"></i> TrendWear
			</div>
			<div>
				Bringing Fashion to You
			</div>
			<div class="footer-note">
				&copy; @footerNote TrendWear. All rights reserved.
			</div>
		</div>
	</footer>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>  
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	@await RenderSectionAsync("Scripts", required: false)  
</body>  
</html>

ClothingBrandApp/Views/Shared/_NotificationsPartial.cshtml
@using static ClothingBrandApp.GCommon.ApplicationConstants

@if (TempData[InfoMessageKey] != null)
{
    <script>toastr.info("@TempData[InfoMessageKey]")</script>
}

@if (TempData[SuccessMessageKey] != null)
{
    <script>toastr.success("@TempData[SuccessMessageKey]")</script>
}

@if (TempData[WarningMessageKey] != null)
{
    <script>toastr.warning("@TempData[WarningMessageKey]")</script>
}

@if (TempData[ErrorMessageKey] != null)
{
    <script>toastr.error("@TempData[ErrorMessageKey]")</script>
}

ClothingBrandApp/Views/Shared/_WarehouseSearchAndFilterPartial.cshtml
@model IEnumerable<string>

<div class="row mb-4">
    <div class="col-md-6">
        <input type="text" id="searchBar" class="form-control shadow-sm" placeholder="Search for a warehouse..." onkeyup="filterWarehouses()">
    </div>
    <div class="col-md-6">
        <select id="cityFilter" class="form-select shadow-sm" onchange="filterWarehouses()">
            <option value="">All Cities</option>
            @foreach (var city in Model)
            {
                <option value="@city">@city</option>
            }
        </select>
    </div>
</div>